### ISSUE TITLE
appveyor example invalid

### ISSUE THREAD

**Issue by wpalfi** [conan-io/docs#1502]
The example in https://docs.conan.io/en/latest/integrations/ci/appveyor.html is invalid (indentation, cmmd). I am new to appveyor. I guess it should be:

```yml
version: 1.0.{build}
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: conan install . -o gtest:shared=True
  - cmd: cd build
  - cmd: cmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin
  - cmd: encryption_test.exe
```
